import streamlit as st
import yfinance as yf
import pandas as pd

st.set_page_config(page_title="Investment Point - Live Data", layout="wide")

st.title("📈 Investment Point: Live Market Dashboard")
st.write("Fetching live data from Yahoo Finance")

# --- SIDEBAR: SEARCH & CUSTOM TICKERS ---

st.sidebar.header("Add New Ticker")
new_ticker = st.sidebar.text_input("Enter Ticker (e.g., SBIN.NS, GOOG):").upper()

# Start with your default list
if 'ticker_list' not in st.session_state:
    st.session_state.ticker_list = {'Nifty 50': '^NSEI', 'Reliance': 'RELIANCE.BSE'}

# Add the new one if the user typed something
if st.sidebar.button("Add to Dashboard") and new_ticker:
    st.session_state.ticker_list[new_ticker] = new_ticker

# Use the list from session_state for display
tickers = st.session_state.ticker_list

# Example of using the updated list in a dropdown
selected_stock = st.selectbox("Select Stock to View", options=list(tickers.keys()))

# Define the symbols
default_tickers = {
    'Nifty 50': '^NSEI',
    'BSE Sensex': '^BSESN',
    'BSE Small Cap': '^BSESMCAP',
    'Reliance (BSE)': 'RELIANCE.BSE',
    'Reliance (BSE)' : 'RELIANCE.BSE',
'Tcs (BSE)' : 'TCS.BSE',
'Hdfcbank (BSE)' : 'HDFCBANK.BSE',
'Icicibank (BSE)' : 'ICICIBANK.BSE',
'Infy (BSE)' : 'INFY.BSE',
'Bhartiartl (BSE)' : 'BHARTIARTL.BSE',
'Hindunilvr (BSE)' : 'HINDUNILVR.BSE',
'Itc (BSE)' : 'ITC.BSE',
'Lici (BSE)' : 'LICI.BSE',
'Sbin (BSE)' : 'SBIN.BSE',
'Lt (BSE)' : 'LT.BSE',
'Bajfinance (BSE)' : 'BAJFINANCE.BSE',
'Hcltech (BSE)' : 'HCLTECH.BSE',
'Kotakbank (BSE)' : 'KOTAKBANK.BSE',
'Titan (BSE)' : 'TITAN.BSE',
'Adanient (BSE)' : 'ADANIENT.BSE',
'Axisbank (BSE)' : 'AXISBANK.BSE',
'Maruti (BSE)' : 'MARUTI.BSE',
'Sunpharma (BSE)' : 'SUNPHARMA.BSE',
'Asianpaint (BSE)' : 'ASIANPAINT.BSE',
'Ntpc (BSE)' : 'NTPC.BSE',
'Tatamotors (BSE)' : 'TATAMOTORS.BSE',
'Tatamtrdvr (BSE)' : 'TATAMTRDVR.BSE',
'Ongc (BSE)' : 'ONGC.BSE',
'Ultracemco (BSE)' : 'ULTRACEMCO.BSE',
'Adanigreen (BSE)' : 'ADANIGREEN.BSE',
'Adaniports (BSE)' : 'ADANIPORTS.BSE',
'Bajajfinsv (BSE)' : 'BAJAJFINSV.BSE',
'Wipro (BSE)' : 'WIPRO.BSE',
'Dmart (BSE)' : 'DMART.BSE',
'Nestleind (BSE)' : 'NESTLEIND.BSE',
'Coalindia (BSE)' : 'COALINDIA.BSE',
'Powergrid (BSE)' : 'POWERGRID.BSE',
'Bajaj-Auto (BSE)' : 'BAJAJ-AUTO.BSE',
'Adanipower (BSE)' : 'ADANIPOWER.BSE',
'M&M (BSE)' : 'M&M.BSE',
'Ioc (BSE)' : 'IOC.BSE',
'Hal (BSE)' : 'HAL.BSE',
'Jswsteel (BSE)' : 'JSWSTEEL.BSE',
'Irfc (BSE)' : 'IRFC.BSE',
'Dlf (BSE)' : 'DLF.BSE',
'Ltim (BSE)' : 'LTIM.BSE',
'Tatasteel (BSE)' : 'TATASTEEL.BSE',
'Vbl (BSE)' : 'VBL.BSE',
'Jiofin (BSE)' : 'JIOFIN.BSE',
'Siemens (BSE)' : 'SIEMENS.BSE',
'Sbilife (BSE)' : 'SBILIFE.BSE',
'Pidilitind (BSE)' : 'PIDILITIND.BSE',
'Grasim (BSE)' : 'GRASIM.BSE',
'Bel (BSE)' : 'BEL.BSE',
'Hindzinc (BSE)' : 'HINDZINC.BSE',
'Hdfclife (BSE)' : 'HDFCLIFE.BSE',
'Pfc (BSE)' : 'PFC.BSE',
'Techm (BSE)' : 'TECHM.BSE',
'Indusindbk (BSE)' : 'INDUSINDBK.BSE',
'Britannia (BSE)' : 'BRITANNIA.BSE',
'Adaniensol (BSE)' : 'ADANIENSOL.BSE',
'Hindalco (BSE)' : 'HINDALCO.BSE',
'Indigo (BSE)' : 'INDIGO.BSE',
'Bankbaroda (BSE)' : 'BANKBARODA.BSE',
'Godrejcp (BSE)' : 'GODREJCP.BSE',
'Recltd (BSE)' : 'RECLTD.BSE',
'Trent (BSE)' : 'TRENT.BSE',
'Tatapower (BSE)' : 'TATAPOWER.BSE',
'Zomato (BSE)' : 'ZOMATO.BSE',
'Atgl (BSE)' : 'ATGL.BSE',
'Lodha (BSE)' : 'LODHA.BSE',
'Cholafin (BSE)' : 'CHOLAFIN.BSE',
'Gail (BSE)' : 'GAIL.BSE',
'Pnb (BSE)' : 'PNB.BSE',
'Tataconsum (BSE)' : 'TATACONSUM.BSE',
'Cipla (BSE)' : 'CIPLA.BSE',
'Ambujacem (BSE)' : 'AMBUJACEM.BSE',
'Eichermot (BSE)' : 'EICHERMOT.BSE',
'Bpcl (BSE)' : 'BPCL.BSE',
'Abb (BSE)' : 'ABB.BSE',
'Divislab (BSE)' : 'DIVISLAB.BSE',
'Vedl (BSE)' : 'VEDL.BSE',
'Unionbank (BSE)' : 'UNIONBANK.BSE',
'Dabur (BSE)' : 'DABUR.BSE',
'Tvsmotor (BSE)' : 'TVSMOTOR.BSE',
'Shreecem (BSE)' : 'SHREECEM.BSE',
'Drreddy (BSE)' : 'DRREDDY.BSE',
'Bajajhldng (BSE)' : 'BAJAJHLDNG.BSE',
'Havells (BSE)' : 'HAVELLS.BSE',
'Mankind (BSE)' : 'MANKIND.BSE',
'Heromotoco (BSE)' : 'HEROMOTOCO.BSE',
'Shriramfin (BSE)' : 'SHRIRAMFIN.BSE',
'Apollohosp (BSE)' : 'APOLLOHOSP.BSE',
'Torntpharm (BSE)' : 'TORNTPHARM.BSE',
'Canbk (BSE)' : 'CANBK.BSE',
'Iob (BSE)' : 'IOB.BSE',
'Jswenergy (BSE)' : 'JSWENERGY.BSE',
'Irctc (BSE)' : 'IRCTC.BSE',
'Tiindia (BSE)' : 'TIINDIA.BSE',
'Icicipruli (BSE)' : 'ICICIPRULI.BSE',
'Idbi (BSE)' : 'IDBI.BSE',
'Jindalstel (BSE)' : 'JINDALSTEL.BSE',
'Idea (BSE)' : 'IDEA.BSE',
'Nhpc (BSE)' : 'NHPC.BSE',
'Motherson (BSE)' : 'MOTHERSON.BSE',
'Bhel (BSE)' : 'BHEL.BSE',
'Zyduslife (BSE)' : 'ZYDUSLIFE.BSE',
'Icicigi (BSE)' : 'ICICIGI.BSE',
'Sbicard (BSE)' : 'SBICARD.BSE',
'Yesbank (BSE)' : 'YESBANK.BSE',
'Hdfcamc (BSE)' : 'HDFCAMC.BSE',
'Maxhealth (BSE)' : 'MAXHEALTH.BSE',
'Cgpower (BSE)' : 'CGPOWER.BSE',
'Bergepaint (BSE)' : 'BERGEPAINT.BSE',
'Srf (BSE)' : 'SRF.BSE',
'Marico (BSE)' : 'MARICO.BSE',
'Colpal (BSE)' : 'COLPAL.BSE',
'Boschltd (BSE)' : 'BOSCHLTD.BSE',
'Naukri (BSE)' : 'NAUKRI.BSE',
'Polycab (BSE)' : 'POLYCAB.BSE',
'Indhotel (BSE)' : 'INDHOTEL.BSE',
'Godrejprop (BSE)' : 'GODREJPROP.BSE',
'Hindpetro (BSE)' : 'HINDPETRO.BSE',
'Lupin (BSE)' : 'LUPIN.BSE',
'Auropharma (BSE)' : 'AUROPHARMA.BSE',
'Solarinds (BSE)' : 'SOLARINDS.BSE',
'Nmdc (BSE)' : 'NMDC.BSE',
'Alkem (BSE)' : 'ALKEM.BSE',
'Bankindia (BSE)' : 'BANKINDIA.BSE',
'Idfcfirstb (BSE)' : 'IDFCFIRSTB.BSE',
'Indianb (BSE)' : 'INDIANB.BSE',
'Ltts (BSE)' : 'LTTS.BSE',
'Persistent (BSE)' : 'PERSISTENT.BSE',
'Mrf (BSE)' : 'MRF.BSE',
'Muthootfin (BSE)' : 'MUTHOOTFIN.BSE',
'Industower (BSE)' : 'INDUSTOWER.BSE',
'Patanjali (BSE)' : 'PATANJALI.BSE',
'Bharatforg (BSE)' : 'BHARATFORG.BSE',
'Pghh (BSE)' : 'PGHH.BSE',
'Cumminsind (BSE)' : 'CUMMINSIND.BSE',
'Oberoirlty (BSE)' : 'OBEROIRLTY.BSE',
'Suzlon (BSE)' : 'SUZLON.BSE',
'Abbotindia (BSE)' : 'ABBOTINDIA.BSE',
'Gicre (BSE)' : 'GICRE.BSE',
'Tataelxsi (BSE)' : 'TATAELXSI.BSE',
'Schaeffler (BSE)' : 'SCHAEFFLER.BSE',
'Fact (BSE)' : 'FACT.BSE',
'Piind (BSE)' : 'PIIND.BSE',
'Concor (BSE)' : 'CONCOR.BSE',
'Prestige (BSE)' : 'PRESTIGE.BSE',
'Supremeind (BSE)' : 'SUPREMEIND.BSE',
'Aubank (BSE)' : 'AUBANK.BSE',
'Gmrinfra (BSE)' : 'GMRINFRA.BSE',
'Ashokley (BSE)' : 'ASHOKLEY.BSE',
'Rvnl (BSE)' : 'RVNL.BSE',
'Mphasis (BSE)' : 'MPHASIS.BSE',
'Balkrisind (BSE)' : 'BALKRISIND.BSE',
'Ucobank (BSE)' : 'UCOBANK.BSE',
'Tatacomm (BSE)' : 'TATACOMM.BSE',
'Ubl (BSE)' : 'UBL.BSE',
'Mazdock (BSE)' : 'MAZDOCK.BSE',
'Torntpower (BSE)' : 'TORNTPOWER.BSE',
'Jsl (BSE)' : 'JSL.BSE',
'Nykaa (BSE)' : 'NYKAA.BSE',
'Astral (BSE)' : 'ASTRAL.BSE',
'Paytm (BSE)' : 'PAYTM.BSE',
'Sail (BSE)' : 'SAIL.BSE',
'Lindeindia (BSE)' : 'LINDEINDIA.BSE',
'Awl (BSE)' : 'AWL.BSE',
'Abcapital (BSE)' : 'ABCAPITAL.BSE',
'Centralbk (BSE)' : 'CENTRALBK.BSE',
'Ofss (BSE)' : 'OFSS.BSE',
'Jswinfra (BSE)' : 'JSWINFRA.BSE',
'Phoenixltd (BSE)' : 'PHOENIXLTD.BSE',
'Acc (BSE)' : 'ACC.BSE',
'L&Tfh (BSE)' : 'L&TFH.BSE',
'Pageind (BSE)' : 'PAGEIND.BSE',
'Aplapollo (BSE)' : 'APLAPOLLO.BSE',
'Kpittech (BSE)' : 'KPITTECH.BSE',
'Upl (BSE)' : 'UPL.BSE',
'Oil (BSE)' : 'OIL.BSE',
'Dalbharat (BSE)' : 'DALBHARAT.BSE',
'Coforge (BSE)' : 'COFORGE.BSE',
'Sjvn (BSE)' : 'SJVN.BSE',
'Unominda (BSE)' : 'UNOMINDA.BSE',
'Sundarmfin (BSE)' : 'SUNDARMFIN.BSE',
'Policybzr (BSE)' : 'POLICYBZR.BSE',
'3Mindia (BSE)' : '3MINDIA.BSE',
'Glaxo (BSE)' : 'GLAXO.BSE',
'Gujgasltd (BSE)' : 'GUJGASLTD.BSE',
'Dixon (BSE)' : 'DIXON.BSE',
'Fluorochem (BSE)' : 'FLUOROCHEM.BSE',
'Unitdspr (BSE)' : 'UNITDSPR.BSE',
'Kalyankjil (BSE)' : 'KALYANKJIL.BSE',
'Poonawalla (BSE)' : 'POONAWALLA.BSE',
'Bandhanbnk (BSE)' : 'BANDHANBNK.BSE',
'Niacl (BSE)' : 'NIACL.BSE',
'Federalbnk (BSE)' : 'FEDERALBNK.BSE',
'Mahabank (BSE)' : 'MAHABANK.BSE',
'Iti (BSE)' : 'ITI.BSE',
'Aiaeng (BSE)' : 'AIAENG.BSE',
'Petronet (BSE)' : 'PETRONET.BSE',
'Voltas (BSE)' : 'VOLTAS.BSE',
'Thermax (BSE)' : 'THERMAX.BSE',
'Jublfood (BSE)' : 'JUBLFOOD.BSE',
'M&Mfin (BSE)' : 'M&MFIN.BSE',
'Coromandel (BSE)' : 'COROMANDEL.BSE',
'Sonacoms (BSE)' : 'SONACOMS.BSE',
'Biocon (BSE)' : 'BIOCON.BSE',
'Metrobrand (BSE)' : 'METROBRAND.BSE',
'Embassy (BSE)' : 'EMBASSY.BSE',
'Honaut (BSE)' : 'HONAUT.BSE',
'Starhealth (BSE)' : 'STARHEALTH.BSE',
'Gland (BSE)' : 'GLAND.BSE',
'Bdl (BSE)' : 'BDL.BSE',
'Nlcindia (BSE)' : 'NLCINDIA.BSE',
'Mfsl (BSE)' : 'MFSL.BSE',
'Deepakntr (BSE)' : 'DEEPAKNTR.BSE',
'Lichsgfin (BSE)' : 'LICHSGFIN.BSE',
'Fortis (BSE)' : 'FORTIS.BSE',
'Zfcvindia (BSE)' : 'ZFCVINDIA.BSE',
'Escorts (BSE)' : 'ESCORTS.BSE',
'Jkcement (BSE)' : 'JKCEMENT.BSE',
'Nam-India (BSE)' : 'NAM-INDIA.BSE',
'Igl (BSE)' : 'IGL.BSE',
'Psb (BSE)' : 'PSB.BSE',
'Mrpl (BSE)' : 'MRPL.BSE',
'Crisil (BSE)' : 'CRISIL.BSE',
'Apollotyre (BSE)' : 'APOLLOTYRE.BSE',
'Delhivery (BSE)' : 'DELHIVERY.BSE',
'Lloydsme (BSE)' : 'LLOYDSME.BSE',
'Endurance (BSE)' : 'ENDURANCE.BSE',
'Ipcalab (BSE)' : 'IPCALAB.BSE',
'Kei (BSE)' : 'KEI.BSE',
'Ajantpharm (BSE)' : 'AJANTPHARM.BSE',
'Manyavar (BSE)' : 'MANYAVAR.BSE',
'Syngene (BSE)' : 'SYNGENE.BSE',
'Angelone (BSE)' : 'ANGELONE.BSE',
'Medanta (BSE)' : 'MEDANTA.BSE',
'Tatachem (BSE)' : 'TATACHEM.BSE',
'Hudco (BSE)' : 'HUDCO.BSE',
'Kansainer (BSE)' : 'KANSAINER.BSE',
'Irb (BSE)' : 'IRB.BSE',
'Godrejind (BSE)' : 'GODREJIND.BSE',
'Msumi (BSE)' : 'MSUMI.BSE',
'Exideind (BSE)' : 'EXIDEIND.BSE',
'Kprmill (BSE)' : 'KPRMILL.BSE',
'Bayercrop (BSE)' : 'BAYERCROP.BSE',
'Sundrmfast (BSE)' : 'SUNDRMFAST.BSE',
'Creditacc (BSE)' : 'CREDITACC.BSE',
'Suntv (BSE)' : 'SUNTV.BSE',
'Hatsun (BSE)' : 'HATSUN.BSE',
'Nh (BSE)' : 'NH.BSE',
'Timken (BSE)' : 'TIMKEN.BSE',
'Jbchepharm (BSE)' : 'JBCHEPHARM.BSE',
'Cyient (BSE)' : 'CYIENT.BSE',
'Grindwell (BSE)' : 'GRINDWELL.BSE',
'Hindcopper (BSE)' : 'HINDCOPPER.BSE',
'Isec (BSE)' : 'ISEC.BSE',
'Iifl (BSE)' : 'IIFL.BSE',
'Powerindia (BSE)' : 'POWERINDIA.BSE',
'Glenmark (BSE)' : 'GLENMARK.BSE',
'Nationalum (BSE)' : 'NATIONALUM.BSE',
'Zeel (BSE)' : 'ZEEL.BSE',
'Ratnamani (BSE)' : 'RATNAMANI.BSE',
'360One (BSE)' : '360ONE.BSE',
'Skfindia (BSE)' : 'SKFINDIA.BSE',
'Kiocl (BSE)' : 'KIOCL.BSE',
'Jbma (BSE)' : 'JBMA.BSE',
'Brigade (BSE)' : 'BRIGADE.BSE',
'Devyani (BSE)' : 'DEVYANI.BSE',
'Ramcocem (BSE)' : 'RAMCOCEM.BSE',
'Emamiltd (BSE)' : 'EMAMILTD.BSE',
'Motilalofs (BSE)' : 'MOTILALOFS.BSE',
'Cochinship (BSE)' : 'COCHINSHIP.BSE',
'Trident (BSE)' : 'TRIDENT.BSE',
'Kajariacer (BSE)' : 'KAJARIACER.BSE',
'Lauruslabs (BSE)' : 'LAURUSLABS.BSE',
'Bsoft (BSE)' : 'BSOFT.BSE',
'Relaxo (BSE)' : 'RELAXO.BSE',
'Aparinds (BSE)' : 'APARINDS.BSE',
'Tatainvest (BSE)' : 'TATAINVEST.BSE',
'Bluestarco (BSE)' : 'BLUESTARCO.BSE',
'Asterdm (BSE)' : 'ASTERDM.BSE',
'Carboruniv (BSE)' : 'CARBORUNIV.BSE',
'Radico (BSE)' : 'RADICO.BSE',
'Gillette (BSE)' : 'GILLETTE.BSE',
'Pnbhousing (BSE)' : 'PNBHOUSING.BSE',
'Fivestar (BSE)' : 'FIVESTAR.BSE',
'Abfrl (BSE)' : 'ABFRL.BSE',
'Aartiind (BSE)' : 'AARTIIND.BSE',
'Sonatsoftw (BSE)' : 'SONATSOFTW.BSE',
'Cgcl (BSE)' : 'CGCL.BSE',
'Crompton (BSE)' : 'CROMPTON.BSE',
'Lalpathlab (BSE)' : 'LALPATHLAB.BSE',
'Pel (BSE)' : 'PEL.BSE',
'Sumichem (BSE)' : 'SUMICHEM.BSE',
'Bataindia (BSE)' : 'BATAINDIA.BSE',
'Idfc (BSE)' : 'IDFC.BSE',
'Nxst (BSE)' : 'NXST.BSE',
'Mindspace (BSE)' : 'MINDSPACE.BSE',
'Ircon (BSE)' : 'IRCON.BSE',
'Atul (BSE)' : 'ATUL.BSE',
'Pfizer (BSE)' : 'PFIZER.BSE',
'Sanofi (BSE)' : 'SANOFI.BSE',
'Cholahldng (BSE)' : 'CHOLAHLDNG.BSE',
'Cieindia (BSE)' : 'CIEINDIA.BSE',
'Cello (BSE)' : 'CELLO.BSE',
'Jyothylab (BSE)' : 'JYOTHYLAB.BSE',
'Cesc (BSE)' : 'CESC.BSE',
'Aplltd (BSE)' : 'APLLTD.BSE',
'Pplpharma (BSE)' : 'PPLPHARMA.BSE',
'Shyammetl (BSE)' : 'SHYAMMETL.BSE',
'Affle (BSE)' : 'AFFLE.BSE',
'Gspl (BSE)' : 'GSPL.BSE',
'Eihotel (BSE)' : 'EIHOTEL.BSE',
'Vinatiorga (BSE)' : 'VINATIORGA.BSE',
'Kaynes (BSE)' : 'KAYNES.BSE',
'Whirlpool (BSE)' : 'WHIRLPOOL.BSE',
'Centuryply (BSE)' : 'CENTURYPLY.BSE',
'Mancredit (BSE)' : 'MANCREDIT.BSE',
'Ttml (BSE)' : 'TTML.BSE',
'Elgiequip (BSE)' : 'ELGIEQUIP.BSE',
'Navinfluor (BSE)' : 'NAVINFLUOR.BSE',
'Rblbank (BSE)' : 'RBLBANK.BSE',
'Aptus (BSE)' : 'APTUS.BSE',
'Suvenphar (BSE)' : 'SUVENPHAR.BSE',
'Bluedart (BSE)' : 'BLUEDART.BSE',
'Jindalsaw (BSE)' : 'JINDALSAW.BSE',
'Hscl (BSE)' : 'HSCL.BSE',
'Castrolind (BSE)' : 'CASTROLIND.BSE',
'Get&D (BSE)' : 'GET&D.BSE',
'Alokinds (BSE)' : 'ALOKINDS.BSE',
'Rrkabel (BSE)' : 'RRKABEL.BSE',
'Jaibalaji (BSE)' : 'JAIBALAJI.BSE',
'Bls (BSE)' : 'BLS.BSE',
'Fincables (BSE)' : 'FINCABLES.BSE',
'Tvshltd (BSE)' : 'TVSHLTD.BSE',
'Mcx (BSE)' : 'MCX.BSE',
'Kims (BSE)' : 'KIMS.BSE',
'Chamblfert (BSE)' : 'CHAMBLFERT.BSE',
'Jwl (BSE)' : 'JWL.BSE',
'Tanla (BSE)' : 'TANLA.BSE',
'Nbcc (BSE)' : 'NBCC.BSE',
'Signature (BSE)' : 'SIGNATURE.BSE',
'Kec (BSE)' : 'KEC.BSE',
'Astrazen (BSE)' : 'ASTRAZEN.BSE',
'Clean (BSE)' : 'CLEAN.BSE',
'Centurytex (BSE)' : 'CENTURYTEX.BSE',
'Indiamart (BSE)' : 'INDIAMART.BSE',
'Rhim (BSE)' : 'RHIM.BSE',
'Dcmshriram (BSE)' : 'DCMSHRIRAM.BSE',
'Welcorp (BSE)' : 'WELCORP.BSE',
'Chalet (BSE)' : 'CHALET.BSE',
'Pvrinox (BSE)' : 'PVRINOX.BSE',
'Gmdcltd (BSE)' : 'GMDCLTD.BSE',
'Manappuram (BSE)' : 'MANAPPURAM.BSE',
'Natcopharm (BSE)' : 'NATCOPHARM.BSE',
'Honasa (BSE)' : 'HONASA.BSE',
'Titagarh (BSE)' : 'TITAGARH.BSE',
'Tejasnet (BSE)' : 'TEJASNET.BSE',
'Concordbio (BSE)' : 'CONCORDBIO.BSE',
'Bikaji (BSE)' : 'BIKAJI.BSE',
'Laxmimach (BSE)' : 'LAXMIMACH.BSE',
'Nslnisp (BSE)' : 'NSLNISP.BSE',
'Swanenergy (BSE)' : 'SWANENERGY.BSE',
'Fineorg (BSE)' : 'FINEORG.BSE',
'Happstmnds (BSE)' : 'HAPPSTMNDS.BSE',
'Finpipe (BSE)' : 'FINPIPE.BSE',
'Polymed (BSE)' : 'POLYMED.BSE',
'Inoxwind (BSE)' : 'INOXWIND.BSE',
'Abslamc (BSE)' : 'ABSLAMC.BSE',
'Cams (BSE)' : 'CAMS.BSE',
'Redington (BSE)' : 'REDINGTON.BSE',
'J&Kbank (BSE)' : 'J&KBANK.BSE',
'Rkforge (BSE)' : 'RKFORGE.BSE',
'Fsl (BSE)' : 'FSL.BSE',
'Olectra (BSE)' : 'OLECTRA.BSE',
'Are&M (BSE)' : 'ARE&M.BSE',
'Geship (BSE)' : 'GESHIP.BSE',
'Karurvysya (BSE)' : 'KARURVYSYA.BSE',
'Network18 (BSE)' : 'NETWORK18.BSE',
'Asahiindia (BSE)' : 'ASAHIINDIA.BSE',
'Westlife (BSE)' : 'WESTLIFE.BSE',
'Mahseamles (BSE)' : 'MAHSEAMLES.BSE',
'Iex (BSE)' : 'IEX.BSE',
'Zensartech (BSE)' : 'ZENSARTECH.BSE',
'Eclerx (BSE)' : 'ECLERX.BSE',
'Triturbine (BSE)' : 'TRITURBINE.BSE',
'Beml (BSE)' : 'BEML.BSE',
'Hblpower (BSE)' : 'HBLPOWER.BSE',
'Sfl (BSE)' : 'SFL.BSE',
'Rites (BSE)' : 'RITES.BSE',
'Basf (BSE)' : 'BASF.BSE',
'Chennpetro (BSE)' : 'CHENNPETRO.BSE',
'Vguard (BSE)' : 'VGUARD.BSE',
'Sobha (BSE)' : 'SOBHA.BSE',
'Amber (BSE)' : 'AMBER.BSE',
'Rainbow (BSE)' : 'RAINBOW.BSE',
'Equitasbnk (BSE)' : 'EQUITASBNK.BSE',
'Mgl (BSE)' : 'MGL.BSE',
'Akzoindia (BSE)' : 'AKZOINDIA.BSE',
'Alkylamine (BSE)' : 'ALKYLAMINE.BSE',
'Eris (BSE)' : 'ERIS.BSE',
'Nuvoco (BSE)' : 'NUVOCO.BSE',
'Enginersin (BSE)' : 'ENGINERSIN.BSE',
'Newgen (BSE)' : 'NEWGEN.BSE',
'Ncc (BSE)' : 'NCC.BSE',
'Sparc (BSE)' : 'SPARC.BSE',
'Aavas (BSE)' : 'AAVAS.BSE',
'Nuvama (BSE)' : 'NUVAMA.BSE',
'Raymond (BSE)' : 'RAYMOND.BSE',
'Hfcl (BSE)' : 'HFCL.BSE',
'Kpil (BSE)' : 'KPIL.BSE',
'Bajajelec (BSE)' : 'BAJAJELEC.BSE',
'Intellect (BSE)' : 'INTELLECT.BSE',
'Ksb (BSE)' : 'KSB.BSE',
'Railtel (BSE)' : 'RAILTEL.BSE',
'Aether (BSE)' : 'AETHER.BSE',
'Vtl (BSE)' : 'VTL.BSE',
'Ujjivansfb (BSE)' : 'UJJIVANSFB.BSE',
'Elecon (BSE)' : 'ELECON.BSE',
'Dbrealty (BSE)' : 'DBREALTY.BSE',
'Rpower (BSE)' : 'RPOWER.BSE',
'Anandrathi (BSE)' : 'ANANDRATHI.BSE',
'Gsfc (BSE)' : 'GSFC.BSE',
'Caplipoint (BSE)' : 'CAPLIPOINT.BSE',
'Tv18Brdcst (BSE)' : 'TV18BRDCST.BSE',
'Biret (BSE)' : 'BIRET.BSE',
'Grinfra (BSE)' : 'GRINFRA.BSE',
'Rtnindia (BSE)' : 'RTNINDIA.BSE',
'Godfryphlp (BSE)' : 'GODFRYPHLP.BSE',
'Bbtc (BSE)' : 'BBTC.BSE',
'Datapattns (BSE)' : 'DATAPATTNS.BSE',
'Jppower (BSE)' : 'JPPOWER.BSE',
'Ttkprestig (BSE)' : 'TTKPRESTIG.BSE',
'Graphite (BSE)' : 'GRAPHITE.BSE',
'Utiamc (BSE)' : 'UTIAMC.BSE',
'Gnfc (BSE)' : 'GNFC.BSE',
'Syrma (BSE)' : 'SYRMA.BSE',
'Mapmyindia (BSE)' : 'MAPMYINDIA.BSE',
'Indigrid (BSE)' : 'INDIGRID.BSE',
'Ace (BSE)' : 'ACE.BSE',
'Birlacorpn (BSE)' : 'BIRLACORPN.BSE',
'Cub (BSE)' : 'CUB.BSE',
'Rajeshexpo (BSE)' : 'RAJESHEXPO.BSE',
'Pncinfra (BSE)' : 'PNCINFRA.BSE',
'Lemontree (BSE)' : 'LEMONTREE.BSE',
'Pcbl (BSE)' : 'PCBL.BSE',
'Jktyre (BSE)' : 'JKTYRE.BSE',
'Godrejagro (BSE)' : 'GODREJAGRO.BSE',
'Swsolar (BSE)' : 'SWSOLAR.BSE',
'Cera (BSE)' : 'CERA.BSE',
'Anuras (BSE)' : 'ANURAS.BSE',
'Splpetro (BSE)' : 'SPLPETRO.BSE',
'Zyduswell (BSE)' : 'ZYDUSWELL.BSE',
'Grse (BSE)' : 'GRSE.BSE',
'Eidparry (BSE)' : 'EIDPARRY.BSE',
'Anantraj (BSE)' : 'ANANTRAJ.BSE',
'Granules (BSE)' : 'GRANULES.BSE',
'Ptcil (BSE)' : 'PTCIL.BSE',
'Craftsman (BSE)' : 'CRAFTSMAN.BSE',
'Mmtc (BSE)' : 'MMTC.BSE',
'Route (BSE)' : 'ROUTE.BSE',
'Canfinhome (BSE)' : 'CANFINHOME.BSE',
'Ibulhsgfin (BSE)' : 'IBULHSGFIN.BSE',
'Schneider (BSE)' : 'SCHNEIDER.BSE',

    'TCS (NSE)': 'TCS.NS'
}

# Initialize session state for the ticker list if it doesn't exist
if 'ticker_list' not in st.session_state:
    st.session_state.ticker_list = default_tickers

# Add user input to the list
if st.sidebar.button("Add to Dashboard") and new_ticker:
    st.session_state.ticker_list[new_ticker] = new_ticker
    st.sidebar.success(f"Added {new_ticker}")

# Use the combined list for display
tickers = st.session_state.ticker_list

# --- MAIN DISPLAY: GRID LAYOUT ---
# We define how many columns we want per row (e.g., 4 or 5)
cols_per_row = 4
ticker_keys = list(tickers.keys())

# Loop through tickers and create rows
for i in range(0, len(ticker_keys), cols_per_row):
    row_tickers = ticker_keys[i:i + cols_per_row]
    cols = st.columns(cols_per_row)
    
    for j, name in enumerate(row_tickers):
        symbol = tickers[name]
        try:
            ticker_obj = yf.Ticker(symbol)
            data = ticker_obj.history(period='2d')
            
            if len(data) >= 1:
                current_price = data['Close'].iloc[-1]
                if len(data) > 1:
                    prev_price = data['Close'].iloc[-2]
                    delta = ((current_price - prev_price) / prev_price) * 100
                else:
                    delta = 0
                
                cols[j].metric(label=name, value=f"₹{current_price:,.2f}", delta=f"{delta:.2f}%")
            else:
                cols[j].error(f"No data: {name}")
                
        except Exception as e:
            cols[j].error(f"Error: {name}")

st.divider()
st.info("Note: Data is delayed according to Yahoo Finance terms. Refresh the page to update.")


# Create columns for the dashboard
cols = st.columns(len(tickers))

for i, (name, symbol) in enumerate(tickers.items()):
    try:
        ticker = yf.Ticker(symbol)
        # Use period='2d' to ensure we have the previous close for delta calculation
        data = ticker.history(period='2d')
        
        if len(data) >= 1:
            current_price = data['Close'].iloc[-1]
            # Calculate change if we have at least 2 days of data
            if len(data) > 1:
                prev_price = data['Close'].iloc[-2]
                delta = ((current_price - prev_price) / prev_price) * 100
            else:
                delta = 0
            
            # Display as a professional metric card
            cols[i].metric(label=name, value=f"₹{current_price:,.2f}", delta=f"{delta:.2f}%")
        else:
            cols[i].error(f"No data for {name}")
            
    except Exception as e:
        cols[i].error("Error")

st.divider()
st.info("Note: Data is delayed according to Yahoo Finance terms. Refresh the page to update.")
